---
title: "Final Project - Part 1"
author: "Owen Bachhuber, Melanie Mitton, Magdalene Lo, Corban Lethcoe"
format: 
  html:
    self-contained: true
    code-tools: true
    toc: true
    theme: journal
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
code-fold: show
---
## Motivation and Data Description ##

As reported by the New York Times, tuberculosis (TB) has reclaimed the title of the world’s leading infectious disease killer as of November 2023, after being briefly removed from its long reign by Covid-19. The World Organization reports that nearly 40 percent of people who are living with TB are untreated and undiagnosed. Deaths from tuberculosis remain pronounced, with 1.36 million people dying from tuberculosis in 2022.

This project aims to better contextualize the relationship between a government spending and tuberculosis on a country-by-country basis. We hypothesize that the countries that spend more on healthcare per person also see less deaths from tuberculosis.

Two data sets were chosen for this analysis: 1) the estimated numbers of deaths caused by TB (all forms) among 100,000 residents during the given year from 2000 - 2015 sorted by country, and 2) the average health expenditures per person paid by government entities from 1995 - 2010 expressed in US dollars using the average exchange rate. 

The data sets were joined by country and only complete observations from 2000 - 2010 were included.

## Data Cleaaning ##


```{r}
library(tidyverse)
library(here)

tb_deaths_long <- read_csv(here("all_forms_of_tb_deaths_per_100000_estimated.csv"))
gov_health_spending_long <- read_csv(here("government_health_spending_per_person_us.csv"))

# Pivot the Tuberculosis Deaths Data
tb_deaths_long <- tb_deaths_long |> 
  pivot_longer(cols = -country, names_to = "year", values_to = "deaths_per_100k", names_prefix = "X") |> 
  mutate(year = as.integer(year)) |> 
  drop_na()

# Pivot the Government Health Spending Data
gov_health_spending_long <- gov_health_spending_long |> 
  pivot_longer(cols = -country, names_to = "year", values_to = "gov_health_spending_usd", names_prefix = "X") |> 
  mutate(year = as.integer(year)) |> 
  drop_na()

# Join the cleaned, long-format datasets
combined_dataset_long_cleaned <- left_join(tb_deaths_long, gov_health_spending_long, by = c("country", "year"))

# Remove any remaining rows with NAs
combined_dataset_long_cleaned <- drop_na(combined_dataset_long_cleaned)

# Write the cleaned, combined dataset to a CSV file
write_csv(combined_dataset_long_cleaned, here("combined_dataset_long_cleaned.csv"))

```
